// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MembershipPlanType string

const (
	MembershipPlanTypeFree   MembershipPlanType = "free"
	MembershipPlanTypeBronze MembershipPlanType = "bronze"
	MembershipPlanTypeSilver MembershipPlanType = "silver"
	MembershipPlanTypeGold   MembershipPlanType = "gold"
	MembershipPlanTypeNA     MembershipPlanType = "n/a"
)

func (e *MembershipPlanType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipPlanType(s)
	case string:
		*e = MembershipPlanType(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipPlanType: %T", src)
	}
	return nil
}

type NullMembershipPlanType struct {
	MembershipPlanType MembershipPlanType `json:"membership_plan_type"`
	Valid              bool               `json:"valid"` // Valid is true if MembershipPlanType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipPlanType) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipPlanType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipPlanType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipPlanType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipPlanType), nil
}

type ReactionType string

const (
	ReactionTypeLike    ReactionType = "like"
	ReactionTypeDislike ReactionType = "dislike"
	ReactionTypeLove    ReactionType = "love"
	ReactionTypeLaugh   ReactionType = "laugh"
	ReactionTypeAngry   ReactionType = "angry"
)

func (e *ReactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReactionType(s)
	case string:
		*e = ReactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReactionType: %T", src)
	}
	return nil
}

type NullReactionType struct {
	ReactionType ReactionType `json:"reaction_type"`
	Valid        bool         `json:"valid"` // Valid is true if ReactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReactionType) Scan(value interface{}) error {
	if value == nil {
		ns.ReactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReactionType), nil
}

type TargetTypeEnum string

const (
	TargetTypeEnumPost    TargetTypeEnum = "post"
	TargetTypeEnumComment TargetTypeEnum = "comment"
)

func (e *TargetTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TargetTypeEnum(s)
	case string:
		*e = TargetTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TargetTypeEnum: %T", src)
	}
	return nil
}

type NullTargetTypeEnum struct {
	TargetTypeEnum TargetTypeEnum `json:"target_type_enum"`
	Valid          bool           `json:"valid"` // Valid is true if TargetTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTargetTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TargetTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TargetTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTargetTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TargetTypeEnum), nil
}

type UserRole string

const (
	UserRoleUser   UserRole = "user"
	UserRoleAdmin  UserRole = "admin"
	UserRoleWriter UserRole = "writer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Archive struct {
	ID        uuid.UUID          `json:"id"`
	PostID    uuid.UUID          `json:"post_id"`
	Name      string             `json:"name"`
	SizeBytes int64              `json:"size_bytes"`
	Pages     int32              `json:"pages"`
	Locations []byte             `json:"locations"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ArchiveStat struct {
	ArchiveID uuid.UUID `json:"archive_id"`
	Downloads int64     `json:"downloads"`
}

type Blogpost struct {
	ID           uuid.UUID          `json:"id"`
	Title        string             `json:"title"`
	AuthorName   string             `json:"author_name"`
	UploaderID   string             `json:"uploader_id"`
	CategoryID   uuid.UUID          `json:"category_id"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	Cover        []byte             `json:"cover"`
	Previews     []byte             `json:"previews"`
	Rating       pgtype.Numeric     `json:"rating"`
	LanguageCode string             `json:"language_code"`
	Pages        int32              `json:"pages"`
	SizeBytes    int64              `json:"size_bytes"`
	MimeTypes    []string           `json:"mime_types"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type BlogpostStat struct {
	PostID    uuid.UUID `json:"post_id"`
	Comments  int64     `json:"comments"`
	Downloads int64     `json:"downloads"`
	AuthViews int64     `json:"auth_views"`
	AnonViews int64     `json:"anon_views"`
}

type Category struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        uuid.UUID          `json:"id"`
	PostID    uuid.UUID          `json:"post_id"`
	ParentID  uuid.NullUUID      `json:"parent_id"`
	Depth     int32              `json:"depth"`
	UserID    string             `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID            uuid.UUID     `json:"id"`
	Name          *string       `json:"name"`
	IsGroup       bool          `json:"is_group"`
	LastMessageID uuid.NullUUID `json:"last_message_id"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type ConversationParticipant struct {
	ConversationID    uuid.UUID     `json:"conversation_id"`
	UserID            string        `json:"user_id"`
	JoinedAt          time.Time     `json:"joined_at"`
	LastReadMessageID uuid.NullUUID `json:"last_read_message_id"`
}

type DailyEngagement struct {
	Date            pgtype.Date        `json:"date"`
	TotalDownloads  *int32             `json:"total_downloads"`
	Total404Errors  *int32             `json:"total_404_errors"`
	AvgSessionDepth pgtype.Numeric     `json:"avg_session_depth"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DashboardSnapshot struct {
	SnapshotDate     pgtype.Date        `json:"snapshot_date"`
	TotalRevenue     pgtype.Numeric     `json:"total_revenue"`
	ActiveUsers      int32              `json:"active_users"`
	PlanDistribution []byte             `json:"plan_distribution"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       string    `json:"sender_id"`
	Content        string    `json:"content"`
	SentAt         time.Time `json:"sent_at"`
}

type Reaction struct {
	ID           uuid.UUID          `json:"id"`
	UserID       string             `json:"user_id"`
	TargetID     uuid.UUID          `json:"target_id"`
	TargetType   TargetTypeEnum     `json:"target_type"`
	ReactionType ReactionType       `json:"reaction_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SocialEngagement struct {
	Date      pgtype.Date        `json:"date"`
	Comments  int32              `json:"comments"`
	Messages  int32              `json:"messages"`
	Reactions int32              `json:"reactions"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SystemStat struct {
	EntityName string `json:"entity_name"`
	TotalCount int64  `json:"total_count"`
}

type User struct {
	ID             string                 `json:"id"`
	Name           string                 `json:"name"`
	Email          string                 `json:"email"`
	EmailVerified  bool                   `json:"email_verified"`
	Image          *string                `json:"image"`
	Role           NullUserRole           `json:"role"`
	MembershipPlan NullMembershipPlanType `json:"membership_plan"`
	Banned         *bool                  `json:"banned"`
	BanReason      *string                `json:"ban_reason"`
	BanExpires     pgtype.Timestamptz     `json:"ban_expires"`
	CreatedAt      time.Time              `json:"created_at"`
	UpdatedAt      time.Time              `json:"updated_at"`
}
