// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) error
	// =============================================================================
	// COMMENT QUERIES (v3 Compatible)
	// =============================================================================
	// Note: Depth is calculated automatically by the DB trigger.
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	// =============================================================================
	// MESSAGING QUERIES (v3 Compatible)
	// =============================================================================
	CreateConversation(ctx context.Context, arg CreateConversationParams) (uuid.UUID, error)
	DeleteArchive(ctx context.Context, id uuid.UUID) error
	// Cascade handles nested replies.
	DeleteComment(ctx context.Context, id uuid.UUID) error
	DeleteConversation(ctx context.Context, id uuid.UUID) error
	DeletePost(ctx context.Context, id uuid.UUID) error
	GetArchiveByID(ctx context.Context, id uuid.UUID) (GetArchiveByIDRow, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error)
	// Useful if your Go code wants to enforce a max nesting limit (e.g., max 5 levels).
	GetCommentDepth(ctx context.Context, id uuid.UUID) (int32, error)
	// Uses a Recursive CTE to fetch the entire hierarchy for a post in one trip.
	GetCommentsByPostID(ctx context.Context, postID uuid.UUID) ([]GetCommentsByPostIDRow, error)
	// Finds an existing 1-on-1 conversation between exactly two users.
	// Better-Auth user IDs are TEXT.
	GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (uuid.UUID, error)
	// Cursor-based pagination using UUID v7 (Time-ordered)
	GetMessagesBefore(ctx context.Context, arg GetMessagesBeforeParams) ([]GetMessagesBeforeRow, error)
	GetOrCreateDirectConversation(ctx context.Context, arg GetOrCreateDirectConversationParams) (interface{}, error)
	GetPostArchives(ctx context.Context, postID uuid.UUID) ([]GetPostArchivesRow, error)
	GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error)
	// Aggregate counts for a target. target_id is UUID.
	GetReactionSummary(ctx context.Context, arg GetReactionSummaryParams) (GetReactionSummaryRow, error)
	// Get a user's current reaction on a target (NULL if none)
	GetUserReaction(ctx context.Context, arg GetUserReactionParams) (ReactionType, error)
	// Updates the separate stats table to avoid locking the main archive table.
	IncrementDownloadCount(ctx context.Context, archiveID uuid.UUID) error
	IncrementPostView(ctx context.Context, arg IncrementPostViewParams) error
	// Using UUID v7 for the ID (handled by DEFAULT in schema)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	ListArchivesByPostID(ctx context.Context, postID uuid.UUID) ([]ListArchivesByPostIDRow, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error)
	ListPostsByTags(ctx context.Context, arg ListPostsByTagsParams) ([]ListPostsByTagsRow, error)
	ListPostsByTagsFlexible(ctx context.Context, arg ListPostsByTagsFlexibleParams) ([]ListPostsByTagsFlexibleRow, error)
	// Fetches chat list for a user with unread counts and the last message content.
	ListUserConversations(ctx context.Context, userID string) ([]ListUserConversationsRow, error)
	// Remove any reaction from a user on a target
	RemoveReaction(ctx context.Context, arg RemoveReactionParams) error
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error)
	// This handles both increment (amount = 1) and decrement (amount = -1)
	UpdateArchiveDownloads(ctx context.Context, arg UpdateArchiveDownloadsParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error
	UpsertArchive(ctx context.Context, arg UpsertArchiveParams) (uuid.UUID, error)
	UpsertBlogPost(ctx context.Context, arg UpsertBlogPostParams) (Blogpost, error)
	// =============================================================================
	// REACTION QUERIES
	// =============================================================================
	// Insert or update a reaction (toggle/switch like ↔ unlike)
	// user_id is TEXT (Better-Auth), target_id is UUID (Post/Comment)
	UpsertReaction(ctx context.Context, arg UpsertReactionParams) error
}

var _ Querier = (*Queries)(nil)
