// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO conversation_participants (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT (conversation_id, user_id) DO NOTHING
`

type AddParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.ConversationID, arg.UserID)
	return err
}

const createComment = `-- name: CreateComment :one

INSERT INTO comments (post_id,
                      parent_id,
                      user_id,
                      content)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, parent_id, depth, user_id, content, created_at
`

type CreateCommentParams struct {
	PostID   uuid.UUID     `json:"post_id"`
	ParentID uuid.NullUUID `json:"parent_id"`
	UserID   string        `json:"user_id"`
	Content  string        `json:"content"`
}

// =============================================================================
// COMMENT QUERIES (v3 Compatible)
// =============================================================================
// Note: Depth is calculated automatically by the DB trigger.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.ParentID,
		arg.UserID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.Depth,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one

INSERT INTO conversations (name, is_group)
VALUES ($1, $2)
RETURNING id
`

type CreateConversationParams struct {
	Name    *string `json:"name"`
	IsGroup bool    `json:"is_group"`
}

// =============================================================================
// MESSAGING QUERIES (v3 Compatible)
// =============================================================================
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Name, arg.IsGroup)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteArchive = `-- name: DeleteArchive :exec
DELETE
FROM archives
WHERE id = $1
`

func (q *Queries) DeleteArchive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArchive, id)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE
FROM comments
WHERE id = $1
`

// Cascade handles nested replies.
func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE
FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE
FROM blogposts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getArchiveByID = `-- name: GetArchiveByID :one
SELECT a.id, a.post_id, a.name, a.size_bytes, a.pages, a.locations, a.updated_at, a.created_at, s.archive_id, s.downloads
FROM archives a
         LEFT JOIN archive_stats s ON a.id = s.archive_id
WHERE a.id = $1
`

type GetArchiveByIDRow struct {
	Archive     Archive     `json:"archive"`
	ArchiveStat ArchiveStat `json:"archive_stat"`
}

func (q *Queries) GetArchiveByID(ctx context.Context, id uuid.UUID) (GetArchiveByIDRow, error) {
	row := q.db.QueryRow(ctx, getArchiveByID, id)
	var i GetArchiveByIDRow
	err := row.Scan(
		&i.Archive.ID,
		&i.Archive.PostID,
		&i.Archive.Name,
		&i.Archive.SizeBytes,
		&i.Archive.Pages,
		&i.Archive.Locations,
		&i.Archive.UpdatedAt,
		&i.Archive.CreatedAt,
		&i.ArchiveStat.ArchiveID,
		&i.ArchiveStat.Downloads,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, post_id, parent_id, depth, user_id, content, created_at
FROM comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.Depth,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentDepth = `-- name: GetCommentDepth :one
SELECT depth
FROM comments
WHERE id = $1
`

// Useful if your Go code wants to enforce a max nesting limit (e.g., max 5 levels).
func (q *Queries) GetCommentDepth(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCommentDepth, id)
	var depth int32
	err := row.Scan(&depth)
	return depth, err
}

const getCommentsByPostID = `-- name: GetCommentsByPostID :many
WITH RECURSIVE comment_tree AS (
    -- 1. Anchor: Root level comments (parent_id is NULL)
    SELECT c.id,
           c.post_id,
           c.parent_id,
           c.depth,
           c.user_id,
           c.content,
           c.created_at
    FROM comments c
    WHERE c.post_id = $1
      AND c.parent_id IS NULL

    UNION ALL

    -- 2. Recursive: Join children to their established parents
    SELECT child.id,
           child.post_id,
           child.parent_id,
           child.depth,
           child.user_id,
           child.content,
           child.created_at
    FROM comments child
             INNER JOIN comment_tree ct ON child.parent_id = ct.id)
SELECT ct.id,
       ct.post_id,
       ct.parent_id,
       ct.depth,
       ct.user_id,
       ct.content,
       ct.created_at
FROM comment_tree ct
ORDER BY ct.depth ASC, ct.created_at ASC
`

type GetCommentsByPostIDRow struct {
	ID        uuid.UUID          `json:"id"`
	PostID    uuid.UUID          `json:"post_id"`
	ParentID  uuid.NullUUID      `json:"parent_id"`
	Depth     int32              `json:"depth"`
	UserID    string             `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Uses a Recursive CTE to fetch the entire hierarchy for a post in one trip.
func (q *Queries) GetCommentsByPostID(ctx context.Context, postID uuid.UUID) ([]GetCommentsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentsByPostIDRow{}
	for rows.Next() {
		var i GetCommentsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.Depth,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectConversation = `-- name: GetDirectConversation :one
SELECT c.id AS conversation_id
FROM conversations c
WHERE c.is_group = FALSE
  AND EXISTS (SELECT 1 FROM conversation_participants cp WHERE cp.conversation_id = c.id AND cp.user_id = $1)
  AND EXISTS (SELECT 1 FROM conversation_participants cp WHERE cp.conversation_id = c.id AND cp.user_id = $2)
  AND (SELECT COUNT(*) FROM conversation_participants WHERE conversation_id = c.id) = 2
LIMIT 1
`

type GetDirectConversationParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

// Finds an existing 1-on-1 conversation between exactly two users.
// Better-Auth user IDs are TEXT.
func (q *Queries) GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDirectConversation, arg.UserID, arg.UserID_2)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getMessagesBefore = `-- name: GetMessagesBefore :many
SELECT m.id,
       m.conversation_id,
       m.sender_id,
       u.name  AS sender_name,
       u.image AS sender_image,
       m.content,
       m.sent_at
FROM messages m
         JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = $1
  -- If cursor is null, get latest. If provided, get older (ID < cursor)
  AND ($3::uuid IS NULL OR m.id < $3)
ORDER BY m.id DESC
LIMIT $2
`

type GetMessagesBeforeParams struct {
	ConversationID uuid.UUID     `json:"conversation_id"`
	Limit          int32         `json:"limit"`
	Cursor         uuid.NullUUID `json:"cursor"`
}

type GetMessagesBeforeRow struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       string    `json:"sender_id"`
	SenderName     string    `json:"sender_name"`
	SenderImage    *string   `json:"sender_image"`
	Content        string    `json:"content"`
	SentAt         time.Time `json:"sent_at"`
}

// Cursor-based pagination using UUID v7 (Time-ordered)
func (q *Queries) GetMessagesBefore(ctx context.Context, arg GetMessagesBeforeParams) ([]GetMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, getMessagesBefore, arg.ConversationID, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesBeforeRow{}
	for rows.Next() {
		var i GetMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderName,
			&i.SenderImage,
			&i.Content,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateDirectConversation = `-- name: GetOrCreateDirectConversation :one
SELECT get_or_create_direct_conversation($1, $2) AS conversation_id
`

type GetOrCreateDirectConversationParams struct {
	GetOrCreateDirectConversation   interface{} `json:"get_or_create_direct_conversation"`
	GetOrCreateDirectConversation_2 interface{} `json:"get_or_create_direct_conversation_2"`
}

func (q *Queries) GetOrCreateDirectConversation(ctx context.Context, arg GetOrCreateDirectConversationParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getOrCreateDirectConversation, arg.GetOrCreateDirectConversation, arg.GetOrCreateDirectConversation_2)
	var conversation_id interface{}
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getPostArchives = `-- name: GetPostArchives :many
SELECT a.id, a.post_id, a.name, a.size_bytes, a.pages, a.locations, a.updated_at, a.created_at, s.archive_id, s.downloads
FROM archives a
         JOIN archive_stats s ON a.id = s.archive_id
WHERE a.post_id = $1
`

type GetPostArchivesRow struct {
	Archive     Archive     `json:"archive"`
	ArchiveStat ArchiveStat `json:"archive_stat"`
}

func (q *Queries) GetPostArchives(ctx context.Context, postID uuid.UUID) ([]GetPostArchivesRow, error) {
	rows, err := q.db.Query(ctx, getPostArchives, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostArchivesRow{}
	for rows.Next() {
		var i GetPostArchivesRow
		if err := rows.Scan(
			&i.Archive.ID,
			&i.Archive.PostID,
			&i.Archive.Name,
			&i.Archive.SizeBytes,
			&i.Archive.Pages,
			&i.Archive.Locations,
			&i.Archive.UpdatedAt,
			&i.Archive.CreatedAt,
			&i.ArchiveStat.ArchiveID,
			&i.ArchiveStat.Downloads,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT b.id, b.title, b.author_name, b.uploader_id, b.category_id, b.description, b.tags, b.cover, b.previews, b.rating, b.language_code, b.pages, b.size_bytes, b.mime_types, b.created_at, b.updated_at,
       c.id, c.slug, c.display_name, c.created_at,
       s.post_id, s.comments, s.downloads, s.auth_views, s.anon_views
FROM blogposts b
         JOIN categories c ON b.category_id = c.id
         LEFT JOIN blogpost_stats s ON b.id = s.post_id
WHERE b.id = $1
`

type GetPostByIDRow struct {
	Blogpost     Blogpost     `json:"blogpost"`
	Category     Category     `json:"category"`
	BlogpostStat BlogpostStat `json:"blogpost_stat"`
}

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.Blogpost.ID,
		&i.Blogpost.Title,
		&i.Blogpost.AuthorName,
		&i.Blogpost.UploaderID,
		&i.Blogpost.CategoryID,
		&i.Blogpost.Description,
		&i.Blogpost.Tags,
		&i.Blogpost.Cover,
		&i.Blogpost.Previews,
		&i.Blogpost.Rating,
		&i.Blogpost.LanguageCode,
		&i.Blogpost.Pages,
		&i.Blogpost.SizeBytes,
		&i.Blogpost.MimeTypes,
		&i.Blogpost.CreatedAt,
		&i.Blogpost.UpdatedAt,
		&i.Category.ID,
		&i.Category.Slug,
		&i.Category.DisplayName,
		&i.Category.CreatedAt,
		&i.BlogpostStat.PostID,
		&i.BlogpostStat.Comments,
		&i.BlogpostStat.Downloads,
		&i.BlogpostStat.AuthViews,
		&i.BlogpostStat.AnonViews,
	)
	return i, err
}

const getReactionSummary = `-- name: GetReactionSummary :one
SELECT COUNT(*) FILTER (WHERE reaction_type = 'like')::bigint     AS likes,
       COUNT(*) FILTER (WHERE reaction_type = 'unlike')::bigint   AS unlikes,
       (COUNT(*) FILTER (WHERE reaction_type = 'like') -
        COUNT(*) FILTER (WHERE reaction_type = 'unlike'))::bigint AS net_likes
FROM reactions
WHERE target_id = $1
  AND target_type = $2
`

type GetReactionSummaryParams struct {
	TargetID   uuid.UUID      `json:"target_id"`
	TargetType TargetTypeEnum `json:"target_type"`
}

type GetReactionSummaryRow struct {
	Likes    int64 `json:"likes"`
	Unlikes  int64 `json:"unlikes"`
	NetLikes int64 `json:"net_likes"`
}

// Aggregate counts for a target. target_id is UUID.
func (q *Queries) GetReactionSummary(ctx context.Context, arg GetReactionSummaryParams) (GetReactionSummaryRow, error) {
	row := q.db.QueryRow(ctx, getReactionSummary, arg.TargetID, arg.TargetType)
	var i GetReactionSummaryRow
	err := row.Scan(&i.Likes, &i.Unlikes, &i.NetLikes)
	return i, err
}

const getUserReaction = `-- name: GetUserReaction :one
SELECT reaction_type
FROM reactions
WHERE user_id = $1
  AND target_id = $2
  AND target_type = $3
`

type GetUserReactionParams struct {
	UserID     string         `json:"user_id"`
	TargetID   uuid.UUID      `json:"target_id"`
	TargetType TargetTypeEnum `json:"target_type"`
}

// Get a user's current reaction on a target (NULL if none)
func (q *Queries) GetUserReaction(ctx context.Context, arg GetUserReactionParams) (ReactionType, error) {
	row := q.db.QueryRow(ctx, getUserReaction, arg.UserID, arg.TargetID, arg.TargetType)
	var reaction_type ReactionType
	err := row.Scan(&reaction_type)
	return reaction_type, err
}

const incrementDownloadCount = `-- name: IncrementDownloadCount :exec
INSERT INTO archive_stats (archive_id, downloads)
VALUES ($1, 1)
ON CONFLICT (archive_id)
    DO UPDATE SET downloads = archive_stats.downloads + 1
`

// Updates the separate stats table to avoid locking the main archive table.
func (q *Queries) IncrementDownloadCount(ctx context.Context, archiveID uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementDownloadCount, archiveID)
	return err
}

const incrementPostView = `-- name: IncrementPostView :exec
INSERT INTO blogpost_stats (post_id, auth_views, anon_views)
VALUES ($1, $2, $3)
ON CONFLICT (post_id) DO UPDATE SET auth_views = blogpost_stats.auth_views + EXCLUDED.auth_views,
                                    anon_views = blogpost_stats.anon_views + EXCLUDED.anon_views
`

type IncrementPostViewParams struct {
	PostID    uuid.UUID `json:"post_id"`
	AuthViews int64     `json:"auth_views"`
	AnonViews int64     `json:"anon_views"`
}

func (q *Queries) IncrementPostView(ctx context.Context, arg IncrementPostViewParams) error {
	_, err := q.db.Exec(ctx, incrementPostView, arg.PostID, arg.AuthViews, arg.AnonViews)
	return err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, content, sent_at
`

type InsertMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       string    `json:"sender_id"`
	Content        string    `json:"content"`
}

// Using UUID v7 for the ID (handled by DEFAULT in schema)
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.SentAt,
	)
	return i, err
}

const listArchivesByPostID = `-- name: ListArchivesByPostID :many
SELECT a.id, a.post_id, a.name, a.size_bytes, a.pages, a.locations, a.updated_at, a.created_at, s.archive_id, s.downloads
FROM archives a
         LEFT JOIN archive_stats s ON a.id = s.archive_id
WHERE a.post_id = $1
ORDER BY a.created_at ASC
`

type ListArchivesByPostIDRow struct {
	Archive     Archive     `json:"archive"`
	ArchiveStat ArchiveStat `json:"archive_stat"`
}

func (q *Queries) ListArchivesByPostID(ctx context.Context, postID uuid.UUID) ([]ListArchivesByPostIDRow, error) {
	rows, err := q.db.Query(ctx, listArchivesByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchivesByPostIDRow{}
	for rows.Next() {
		var i ListArchivesByPostIDRow
		if err := rows.Scan(
			&i.Archive.ID,
			&i.Archive.PostID,
			&i.Archive.Name,
			&i.Archive.SizeBytes,
			&i.Archive.Pages,
			&i.Archive.Locations,
			&i.Archive.UpdatedAt,
			&i.Archive.CreatedAt,
			&i.ArchiveStat.ArchiveID,
			&i.ArchiveStat.Downloads,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT b.id, b.title, b.author_name, b.uploader_id, b.category_id, b.description, b.tags, b.cover, b.previews, b.rating, b.language_code, b.pages, b.size_bytes, b.mime_types, b.created_at, b.updated_at,
       c.id, c.slug, c.display_name, c.created_at,
       s.post_id, s.comments, s.downloads, s.auth_views, s.anon_views
FROM blogposts b
         JOIN categories c ON b.category_id = c.id
         LEFT JOIN blogpost_stats s ON b.id = s.post_id
ORDER BY b.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPostsRow struct {
	Blogpost     Blogpost     `json:"blogpost"`
	Category     Category     `json:"category"`
	BlogpostStat BlogpostStat `json:"blogpost_stat"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.Blogpost.ID,
			&i.Blogpost.Title,
			&i.Blogpost.AuthorName,
			&i.Blogpost.UploaderID,
			&i.Blogpost.CategoryID,
			&i.Blogpost.Description,
			&i.Blogpost.Tags,
			&i.Blogpost.Cover,
			&i.Blogpost.Previews,
			&i.Blogpost.Rating,
			&i.Blogpost.LanguageCode,
			&i.Blogpost.Pages,
			&i.Blogpost.SizeBytes,
			&i.Blogpost.MimeTypes,
			&i.Blogpost.CreatedAt,
			&i.Blogpost.UpdatedAt,
			&i.Category.ID,
			&i.Category.Slug,
			&i.Category.DisplayName,
			&i.Category.CreatedAt,
			&i.BlogpostStat.PostID,
			&i.BlogpostStat.Comments,
			&i.BlogpostStat.Downloads,
			&i.BlogpostStat.AuthViews,
			&i.BlogpostStat.AnonViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTags = `-- name: ListPostsByTags :many
SELECT b.id, b.title, b.author_name, b.uploader_id, b.category_id, b.description, b.tags, b.cover, b.previews, b.rating, b.language_code, b.pages, b.size_bytes, b.mime_types, b.created_at, b.updated_at, c.id, c.slug, c.display_name, c.created_at, s.post_id, s.comments, s.downloads, s.auth_views, s.anon_views
FROM blogposts b
         JOIN categories c ON b.category_id = c.id
         LEFT JOIN blogpost_stats s ON b.id = s.post_id
WHERE b.tags @> $1::TEXT[]
ORDER BY b.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByTagsParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
}

type ListPostsByTagsRow struct {
	Blogpost     Blogpost     `json:"blogpost"`
	Category     Category     `json:"category"`
	BlogpostStat BlogpostStat `json:"blogpost_stat"`
}

func (q *Queries) ListPostsByTags(ctx context.Context, arg ListPostsByTagsParams) ([]ListPostsByTagsRow, error) {
	rows, err := q.db.Query(ctx, listPostsByTags, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByTagsRow{}
	for rows.Next() {
		var i ListPostsByTagsRow
		if err := rows.Scan(
			&i.Blogpost.ID,
			&i.Blogpost.Title,
			&i.Blogpost.AuthorName,
			&i.Blogpost.UploaderID,
			&i.Blogpost.CategoryID,
			&i.Blogpost.Description,
			&i.Blogpost.Tags,
			&i.Blogpost.Cover,
			&i.Blogpost.Previews,
			&i.Blogpost.Rating,
			&i.Blogpost.LanguageCode,
			&i.Blogpost.Pages,
			&i.Blogpost.SizeBytes,
			&i.Blogpost.MimeTypes,
			&i.Blogpost.CreatedAt,
			&i.Blogpost.UpdatedAt,
			&i.Category.ID,
			&i.Category.Slug,
			&i.Category.DisplayName,
			&i.Category.CreatedAt,
			&i.BlogpostStat.PostID,
			&i.BlogpostStat.Comments,
			&i.BlogpostStat.Downloads,
			&i.BlogpostStat.AuthViews,
			&i.BlogpostStat.AnonViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTagsFlexible = `-- name: ListPostsByTagsFlexible :many
SELECT b.id, b.title, b.author_name, b.uploader_id, b.category_id, b.description, b.tags, b.cover, b.previews, b.rating, b.language_code, b.pages, b.size_bytes, b.mime_types, b.created_at, b.updated_at, c.id, c.slug, c.display_name, c.created_at, s.post_id, s.comments, s.downloads, s.auth_views, s.anon_views
FROM blogposts b
         JOIN categories c ON b.category_id = c.id
         LEFT JOIN blogpost_stats s ON b.id = s.post_id
WHERE (
          -- If match_all is true, use "Contains" (@>)
          ($1::boolean = true AND b.tags @> $2::text[])
              OR
              -- If match_all is false, use "Overlaps" (&&)
          ($1::boolean = false AND b.tags && $2::text[])
          )
ORDER BY b.created_at DESC
LIMIT $4 OFFSET $3
`

type ListPostsByTagsFlexibleParams struct {
	MatchAll  bool     `json:"match_all"`
	Tags      []string `json:"tags"`
	OffsetVal int32    `json:"offset_val"`
	LimitVal  int32    `json:"limit_val"`
}

type ListPostsByTagsFlexibleRow struct {
	Blogpost     Blogpost     `json:"blogpost"`
	Category     Category     `json:"category"`
	BlogpostStat BlogpostStat `json:"blogpost_stat"`
}

func (q *Queries) ListPostsByTagsFlexible(ctx context.Context, arg ListPostsByTagsFlexibleParams) ([]ListPostsByTagsFlexibleRow, error) {
	rows, err := q.db.Query(ctx, listPostsByTagsFlexible,
		arg.MatchAll,
		arg.Tags,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByTagsFlexibleRow{}
	for rows.Next() {
		var i ListPostsByTagsFlexibleRow
		if err := rows.Scan(
			&i.Blogpost.ID,
			&i.Blogpost.Title,
			&i.Blogpost.AuthorName,
			&i.Blogpost.UploaderID,
			&i.Blogpost.CategoryID,
			&i.Blogpost.Description,
			&i.Blogpost.Tags,
			&i.Blogpost.Cover,
			&i.Blogpost.Previews,
			&i.Blogpost.Rating,
			&i.Blogpost.LanguageCode,
			&i.Blogpost.Pages,
			&i.Blogpost.SizeBytes,
			&i.Blogpost.MimeTypes,
			&i.Blogpost.CreatedAt,
			&i.Blogpost.UpdatedAt,
			&i.Category.ID,
			&i.Category.Slug,
			&i.Category.DisplayName,
			&i.Category.CreatedAt,
			&i.BlogpostStat.PostID,
			&i.BlogpostStat.Comments,
			&i.BlogpostStat.Downloads,
			&i.BlogpostStat.AuthViews,
			&i.BlogpostStat.AnonViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT c.id                                                                                       AS conversation_id,
       c.name                                                                                     AS conversation_name,
       c.is_group,
       c.updated_at,
       m.content                                                                                  AS last_message_content,
       m.sender_id                                                                                AS last_message_sender,
       (SELECT COUNT(*)
        FROM messages msg
        WHERE msg.conversation_id = c.id
          AND msg.id > COALESCE(cp.last_read_message_id, '00000000-0000-0000-0000-000000000000')) AS unread_count
FROM conversation_participants cp
         JOIN conversations c ON cp.conversation_id = c.id
         LEFT JOIN messages m ON c.last_message_id = m.id
WHERE cp.user_id = $1
ORDER BY c.updated_at DESC
`

type ListUserConversationsRow struct {
	ConversationID     uuid.UUID `json:"conversation_id"`
	ConversationName   *string   `json:"conversation_name"`
	IsGroup            bool      `json:"is_group"`
	UpdatedAt          time.Time `json:"updated_at"`
	LastMessageContent *string   `json:"last_message_content"`
	LastMessageSender  *string   `json:"last_message_sender"`
	UnreadCount        int64     `json:"unread_count"`
}

// Fetches chat list for a user with unread counts and the last message content.
func (q *Queries) ListUserConversations(ctx context.Context, userID string) ([]ListUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, listUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserConversationsRow{}
	for rows.Next() {
		var i ListUserConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ConversationName,
			&i.IsGroup,
			&i.UpdatedAt,
			&i.LastMessageContent,
			&i.LastMessageSender,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE
FROM reactions
WHERE user_id = $1
  AND target_id = $2
  AND target_type = $3
`

type RemoveReactionParams struct {
	UserID     string         `json:"user_id"`
	TargetID   uuid.UUID      `json:"target_id"`
	TargetType TargetTypeEnum `json:"target_type"`
}

// Remove any reaction from a user on a target
func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.UserID, arg.TargetID, arg.TargetType)
	return err
}

const searchPosts = `-- name: SearchPosts :many
SELECT b.id, b.title, b.author_name, b.uploader_id, b.category_id, b.description, b.tags, b.cover, b.previews, b.rating, b.language_code, b.pages, b.size_bytes, b.mime_types, b.created_at, b.updated_at, c.id, c.slug, c.display_name, c.created_at, s.post_id, s.comments, s.downloads, s.auth_views, s.anon_views
FROM blogposts b
         JOIN categories c ON b.category_id = c.id
         LEFT JOIN blogpost_stats s ON b.id = s.post_id
WHERE
  -- 1. Optional Category Filter
    ($1::uuid IS NULL OR b.category_id = $1)
  AND
  -- 2. Flexible Tag Filter
    (
        ($2::boolean = true AND b.tags @> $3::text[])
            OR
        ($2::boolean = false AND b.tags && $3::text[])
            OR
        (cardinality($3::text[]) = 0) -- Ignore if no tags provided
        )
  AND
  -- 3. Minimum Rating Filter
    b.rating >= $4::numeric
ORDER BY b.created_at DESC
LIMIT $6 OFFSET $5
`

type SearchPostsParams struct {
	CategoryID uuid.NullUUID  `json:"category_id"`
	MatchAll   bool           `json:"match_all"`
	Tags       []string       `json:"tags"`
	MinRating  pgtype.Numeric `json:"min_rating"`
	OffsetVal  int32          `json:"offset_val"`
	LimitVal   int32          `json:"limit_val"`
}

type SearchPostsRow struct {
	Blogpost     Blogpost     `json:"blogpost"`
	Category     Category     `json:"category"`
	BlogpostStat BlogpostStat `json:"blogpost_stat"`
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts,
		arg.CategoryID,
		arg.MatchAll,
		arg.Tags,
		arg.MinRating,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsRow{}
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.Blogpost.ID,
			&i.Blogpost.Title,
			&i.Blogpost.AuthorName,
			&i.Blogpost.UploaderID,
			&i.Blogpost.CategoryID,
			&i.Blogpost.Description,
			&i.Blogpost.Tags,
			&i.Blogpost.Cover,
			&i.Blogpost.Previews,
			&i.Blogpost.Rating,
			&i.Blogpost.LanguageCode,
			&i.Blogpost.Pages,
			&i.Blogpost.SizeBytes,
			&i.Blogpost.MimeTypes,
			&i.Blogpost.CreatedAt,
			&i.Blogpost.UpdatedAt,
			&i.Category.ID,
			&i.Category.Slug,
			&i.Category.DisplayName,
			&i.Category.CreatedAt,
			&i.BlogpostStat.PostID,
			&i.BlogpostStat.Comments,
			&i.BlogpostStat.Downloads,
			&i.BlogpostStat.AuthViews,
			&i.BlogpostStat.AnonViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArchiveDownloads = `-- name: UpdateArchiveDownloads :exec
INSERT INTO archive_stats (archive_id, downloads)
VALUES ($1, $2)
ON CONFLICT (archive_id) DO UPDATE
    SET downloads = archive_stats.downloads + EXCLUDED.downloads
`

type UpdateArchiveDownloadsParams struct {
	ArchiveID uuid.UUID `json:"archive_id"`
	Downloads int64     `json:"downloads"`
}

// This handles both increment (amount = 1) and decrement (amount = -1)
func (q *Queries) UpdateArchiveDownloads(ctx context.Context, arg UpdateArchiveDownloadsParams) error {
	_, err := q.db.Exec(ctx, updateArchiveDownloads, arg.ArchiveID, arg.Downloads)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2
WHERE id = $1
RETURNING id, post_id, parent_id, depth, user_id, content, created_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.Depth,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const updateLastRead = `-- name: UpdateLastRead :exec
UPDATE conversation_participants
SET last_read_message_id = $1
WHERE conversation_id = $2
  AND user_id = $3
`

type UpdateLastReadParams struct {
	LastReadMessageID uuid.NullUUID `json:"last_read_message_id"`
	ConversationID    uuid.UUID     `json:"conversation_id"`
	UserID            string        `json:"user_id"`
}

func (q *Queries) UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error {
	_, err := q.db.Exec(ctx, updateLastRead, arg.LastReadMessageID, arg.ConversationID, arg.UserID)
	return err
}

const upsertArchive = `-- name: UpsertArchive :one
WITH upserted_archive AS (
    INSERT INTO archives (
                          id, post_id, name, size_bytes, pages, locations, updated_at
        ) VALUES (COALESCE($6::uuid, uuid_generate_v7()),
                  $1, $2, $3, $4, $5, NOW())
        ON CONFLICT (id) DO UPDATE SET
            name = EXCLUDED.name,
            size_bytes = EXCLUDED.size_bytes,
            pages = EXCLUDED.pages,
            locations = EXCLUDED.locations,
            updated_at = NOW()
        RETURNING id, post_id, name, size_bytes, pages, locations, updated_at, created_at),
     stats_init AS (
         -- Ensure a stats row exists for the new/updated archive
         INSERT INTO archive_stats (archive_id, downloads)
             SELECT id, 0 FROM upserted_archive
             ON CONFLICT (archive_id) DO NOTHING)
SELECT u.id
FROM upserted_archive u
`

type UpsertArchiveParams struct {
	PostID    uuid.UUID     `json:"post_id"`
	Name      string        `json:"name"`
	SizeBytes int64         `json:"size_bytes"`
	Pages     int32         `json:"pages"`
	Locations []byte        `json:"locations"`
	ID        uuid.NullUUID `json:"id"`
}

func (q *Queries) UpsertArchive(ctx context.Context, arg UpsertArchiveParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertArchive,
		arg.PostID,
		arg.Name,
		arg.SizeBytes,
		arg.Pages,
		arg.Locations,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertBlogPost = `-- name: UpsertBlogPost :one
INSERT INTO blogposts (id,
                       title,
                       author_name,
                       uploader_id,
                       category_id,
                       description,
                       tags,
                       cover,
                       previews,
                       rating,
                       language_code,
                       pages,
                       size_bytes,
                       mime_types,
                       updated_at)
VALUES (COALESCE($14::uuid, uuid_generate_v7()),
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW())
ON CONFLICT (id) DO UPDATE SET title         = EXCLUDED.title,
                               category_id   = EXCLUDED.category_id,
                               description   = EXCLUDED.description,
                               tags          = EXCLUDED.tags,
                               cover         = EXCLUDED.cover,
                               previews      = EXCLUDED.previews,
                               rating        = EXCLUDED.rating,
                               language_code = EXCLUDED.language_code,
                               pages         = EXCLUDED.pages,
                               size_bytes    = EXCLUDED.size_bytes,
                               mime_types    = EXCLUDED.mime_types,
                               updated_at    = NOW()
RETURNING id, title, author_name, uploader_id, category_id, description, tags, cover, previews, rating, language_code, pages, size_bytes, mime_types, created_at, updated_at
`

type UpsertBlogPostParams struct {
	Title        string         `json:"title"`
	AuthorName   string         `json:"author_name"`
	UploaderID   string         `json:"uploader_id"`
	CategoryID   uuid.UUID      `json:"category_id"`
	Description  string         `json:"description"`
	Tags         []string       `json:"tags"`
	Cover        []byte         `json:"cover"`
	Previews     []byte         `json:"previews"`
	Rating       pgtype.Numeric `json:"rating"`
	LanguageCode string         `json:"language_code"`
	Pages        int32          `json:"pages"`
	SizeBytes    int64          `json:"size_bytes"`
	MimeTypes    []string       `json:"mime_types"`
	ID           uuid.NullUUID  `json:"id"`
}

func (q *Queries) UpsertBlogPost(ctx context.Context, arg UpsertBlogPostParams) (Blogpost, error) {
	row := q.db.QueryRow(ctx, upsertBlogPost,
		arg.Title,
		arg.AuthorName,
		arg.UploaderID,
		arg.CategoryID,
		arg.Description,
		arg.Tags,
		arg.Cover,
		arg.Previews,
		arg.Rating,
		arg.LanguageCode,
		arg.Pages,
		arg.SizeBytes,
		arg.MimeTypes,
		arg.ID,
	)
	var i Blogpost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorName,
		&i.UploaderID,
		&i.CategoryID,
		&i.Description,
		&i.Tags,
		&i.Cover,
		&i.Previews,
		&i.Rating,
		&i.LanguageCode,
		&i.Pages,
		&i.SizeBytes,
		&i.MimeTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReaction = `-- name: UpsertReaction :exec

INSERT INTO reactions (user_id,
                       target_id,
                       target_type,
                       reaction_type)
VALUES ($1, $2, $3, $4::reaction_type)
ON CONFLICT (user_id, target_id, target_type)
    DO UPDATE SET reaction_type = EXCLUDED.reaction_type
`

type UpsertReactionParams struct {
	UserID     string         `json:"user_id"`
	TargetID   uuid.UUID      `json:"target_id"`
	TargetType TargetTypeEnum `json:"target_type"`
	Column4    ReactionType   `json:"column_4"`
}

// =============================================================================
// REACTION QUERIES
// =============================================================================
// Insert or update a reaction (toggle/switch like ↔ unlike)
// user_id is TEXT (Better-Auth), target_id is UUID (Post/Comment)
func (q *Queries) UpsertReaction(ctx context.Context, arg UpsertReactionParams) error {
	_, err := q.db.Exec(ctx, upsertReaction,
		arg.UserID,
		arg.TargetID,
		arg.TargetType,
		arg.Column4,
	)
	return err
}
